name: DESAFIO-GITACTIONS-1

on:
  workflow_dispatch: 
    inputs:
      docker_image: 
        description: Buscar imagem
        required: true
        default: ubuntu:latest


jobs:
  docker_image:
    runs-on: ubuntu-latest
    steps:
    - name: Docker PULL
      run: |
        docker pull ${{inputs.docker_image}}

    - name: Docker Image
      run: |
        docker image 

    - name: Docker Scout
      id: docker-scout
      uses: docker/scout-action@v1
      with:
        command: cves,recommendations,compare
        to-latest: true
        ignore-base: true
        ignore-unchanged: true
        only-fixed: true

  
      











# DESAFIO: CRIAR UM WORKFLOW QUE NÃO FAÇA O START AUTOMATICO, ELE TENHA UM CAMPO PARA COLOCAR UM IMPUT
# ESSE IMPUT VAI SER PASSADO UMA IMAGEM DO DOCKER, ELE DEVE FAZER DOCKER PULL, DEPOIS UM DOCKER IMAGE PARA VER A IMAGE
# USAR O WORKFLOW COMPARTILHADO DO PROPRIO DOCKER PARA USAR O SCOUNT CLI PARA VER O AS VULNERABILIDADES

#Docs usadas:
#
#
#
#
#
