name: Segundo Workflow Linuxtips

#Primeiro Tiggrer - toda vez que um commit for feito ele vai iniciar
on:
  workflow_dispatch #Essa instrução vai fazer com que eu tenha que dar um play para a pipeline rodar

jobs: #Serviço posso dar o nome que eu quiser
  job_1:          #nome
    runs-on: ubuntu-latest         #runner onde isso vai rodar (máquina) - é interessante sempre usar a latest 
    steps:
      - name: Confere versao do ubuntu
        run: cat /etc/os-release

      - name: Exibir uma mensagem
        run: echo "Estou fazendo o curso de Github Actions da Linuxtips" > mensagem.txt

      - name: Qualquer outra coisa
        run: ls -lha

      - name: Ler conteudo do arquivo
        run: cat mensagem.txt

  job_2: 
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: Conferir arquivos
        run: ls -lha
      - name: Ler conteudo do arquivo
        run: cat mensagem.txt
