name: Primeiro Workflow Linuxtips

#Primeiro Tiggrer - toda vez que um commit for feito ele vai iniciar
on:
  push:
    branches:
      - main

jobs: #Serviço posso dar o nome que eu quiser
  giropops:          #nome
    runs-on: ubuntu-latest         #runner onde isso vai rodar (máquina) - é interessante sempre usar a latest 
    steps:
      - name: Confere versao do ubuntu
        run: cat /etc/os-release

      - name: Exibir uma mensagem
        run: echo "Estou fazendo o curso de Github Actions da Linuxtips"
